spring.application.name=ateltica


spring.datasource.url=jdbc:mysql://localhost:3306/atletica_db?createDatabaseIfNotExist=true

spring.datasource.username=root

spring.datasource.password=132322

spring.jpa.hibernate.ddl-auto=update

server.port=8081